/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CascadeSelect: typeof import('primevue/cascadeselect')['default']
    Chart: typeof import('primevue/chart')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Divider: typeof import('primevue/divider')['default']
    DynamicDialog: typeof import('primevue/dynamicdialog')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    Menu: typeof import('primevue/menu')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    PickList: typeof import('primevue/picklist')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SpeedDial: typeof import('primevue/speeddial')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface GlobalDirectives {
    KeyFilter: typeof import('primevue/keyfilter')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
