// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Sidebar {
  h_opened: boolean
  v_opened: boolean
}

export interface State {
  sidebar?: Sidebar
}

export interface Menu {
  label: string
  key?: string | number
  icon?: string
  opened?: boolean
  children?: Menu[]
}
